#c. Write a Python program to create an intersection, Union, difference of sets.
#Khushi Ranpariya 20CE118
set1 = {'one','two','three','four','five'}
set2 = {'one','three','five','seven'}
print(set1|set2) # | used for finding union of elements of both sets 
print(set1&set2) # & used for finding intersection of elements of both sets 
print(set1-set2) # - used for finding difference of elements of both sets 